//
//  WordAssetDemo.swift
//  Learn Up
//
//  Created by PowerMac on 17.01.2024.
//

import Foundation

class WordAssetDemoHindi: WordAssetProtocol {
    static var wordCategory = CategoryWords(title: "25 Hindi Words & Phrases Vol.1", language: .Hindi, id: "hindiDemo", wordList: loadWordList(), isPremium: false, assetPath: LearnUpConfiguration.baseCategoryAssetPath)
    
    static func loadWordList() -> [Word] {
        return [
            // MARK: - Здраствуйте
            Word(id: "528BC134-44D5-4334-A029-C0E1DB97BA50",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "नमस्ते (Namaste)",
         
                 translation: "",
             
                 meaning: "",
                  
                 pronunciation: "",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "नमस्ते (Namaste)",
                 meaningOrigin: "Формальное приветствие, которое обычно используется при первой встрече или при общении с незнакомыми людьми",
                 pronunciationOrigin: "[здр`аствуй'т'э]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Спасибо
            Word(id: "C55273C3-CB85-4E70-B894-ACE0725DDB96",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "धन्यवाद (Dhanyavaad)",
                 translation: "Thank you",
                 meaning: "expression of gratitude",
                 pronunciation: "[spəsʲɪ'bo]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "धन्यवाद (Dhanyavaad)",
                 meaningOrigin: "कृतज्ञता की कण-कण अभिव्यक्ति",
                 pronunciationOrigin: "[спа-си́-бо]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Пожалуйста
            Word(id: "2E81E660-EB45-4299-BC3D-1FBBF0AC38BD",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "कृपया (Kripaya)",
                 translation: "Please",
                 meaning: "Polite expressions of address, request, response to gratitude",
                 pronunciation: "[ˌpliːzɡlædˈliː]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "कृपया (Kripaya)",
                 meaningOrigin: "कृतज्ञता के प्रति विनम्र संबोधन, अनुरोध, प्रतिक्रिया व्यक्त करना",
                 pronunciationOrigin: "[пажалуй’ста]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Простите
            Word(id: "1E8C1BB5-D296-42B0-877B-00E660741CAF",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "माफ़ कीजिए (Maaf kijiye)",
                 translation: "Excuse me",
                 meaning: "Regret for causing inconvenience, discomfort, or distress",
                 pronunciation: "[Prəˈstaɪt]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "माफ़ कीजिए (Maaf kijiye)",
                 meaningOrigin: "उत्पन्न हुई अशांति, असुविधा, कष्ट के कारण खेद है",
                 pronunciationOrigin: "[изв’ин’ит’э]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Да
            Word(id: "EE08B5F3-8A30-41FA-9065-CA7B4B3F11BB",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "हाँ (Haan)",
                 translation: "Yes",
                 meaning: "Agreement with something",
                 pronunciation: "[dæ]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "हाँ (Haan)",
                 meaningOrigin: "किसी बात से सहमत होना",
                 pronunciationOrigin: "[да]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Нет
            Word(id: "9A12A29A-5842-46E9-8B4A-397E4894E13F",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "नहीं (Nahi)",
                 translation: "",
                 meaning: "Disagreement with something",
                 pronunciation: "[nɛt]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "नहीं (Nahi)",
                 meaningOrigin: "किसी बात से सहमत न होना",
                 pronunciationOrigin: "[н’эт]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Как дела?
            Word(id: "FAC41092-A1DC-4129-9FB4-AF2B0C2CD079",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "आप कैसे हैं? (Aap kaise hain?)",
                 translation: "How are you?",
                 meaning: "Greetings, inquiry about current state of affairs.",
                 pronunciation: "[kak dʲɪˈla]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "आप कैसे हैं? (Aap kaise hain?)",
                 meaningOrigin: "अभिवादन, वर्तमान स्थिति के बारे में प्रश्न",
                 pronunciationOrigin: "[к`ак д'ила]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Хорошо
            Word(id: "989D6AEE-BD35-4A75-BFA1-4B418C57BE8E",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "ठीक हूँ (Theek hoon)",
                 translation: "Good",
                 meaning: "As is customary, what is considered beautiful, correct.",
                 pronunciation: "[xɐˈroʂə.]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "ठीक हूँ (Theek hoon)",
                 meaningOrigin: "जैसा कि होना चाहिए, जो सुंदर माना जाता है वह सही है",
                 pronunciationOrigin: "[харашо]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Плохо
            Word(id: "80109E60-838D-45A7-97E6-8030907FE5CF",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "बुरा (Bura)",
                 translation: "Bad",
                 meaning: "Appraisal or expression of dissatisfaction, disappointment",
                 pronunciation: "[ˈploxə]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "बुरा (Bura)",
                 meaningOrigin: "असंतोष, निराशा का मूल्यांकन या अभिव्यक्ति",
                 pronunciationOrigin: "[пл`оха]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Где это?
            Word(id: "BB85F13B-373B-4AE9-B787-4F5D18584F7D",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "यह कहाँ है? (Yeh kahan hai?)",
                 translation: "Where is this?",
                 meaning: "Request for the location or positioning of something.",
                 pronunciation: "[ɡdʲe ɛˈto]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "यह कहाँ है? (Yeh kahan hai?)",
                 meaningOrigin: "किसी चीज़ के स्थान या स्थान का अनुरोध करना",
                 pronunciationOrigin: "[гд'э эта]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Сколько это стоит?
            Word(id: "C7C1215F-546A-4A98-8A63-6AA891BC865B",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "यह कितने का है? (Yeh kitne ka hai?)",
                 translation: "How much does it cost?",
                 meaning: "Inquiry about the price of a specific product or service",
                 pronunciation: "[ˈskolʲkə ɛˈto stojɪt]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "यह कितने का है? (Yeh kitne ka hai?)",
                 meaningOrigin: "किसी भी उत्पाद या सेवा के लिए मूल्य का अनुरोध करें",
                 pronunciationOrigin: "[ск`ол'ка эта стои́т]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Можно помочь?
            Word(id: "ACFBC464-D657-4E84-8F09-F0E99C6C4937",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "क्या मैं आपकी मदद कर सकता हूँ? (Kya main aapki madad kar sakta hoon?)",
                 translation: "Can you help?",
                 meaning: "Expression of readiness to provide assistance or support",
                 pronunciation: "[ˈmoʐnə pamɐʂˈtʲi.]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "क्या मैं आपकी मदद कर सकता हूँ? (Kya main aapki madad kar sakta hoon?)",
                 meaningOrigin: "सहायता या समर्थन प्रदान करने की तत्परता की अभिव्यक्ति",
                 pronunciationOrigin: "[можна пам`оч']",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я не понимаю
            Word(id: "E2794BD0-19E2-4130-8D36-88D473D70BD0",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "मैं समझा नहीं (Main samjha nahi)",
                 translation: "I don't understand",
                 meaning: "Expression of not understanding something.",
                 pronunciation: "[ja nʲɪ pɐnʲɪˈmaju]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "मैं समझा नहीं (Main samjha nahi)",
                 meaningOrigin: "यह व्यक्त करना कि वक्ता को कुछ समझ नहीं आ रहा है",
                 pronunciationOrigin: "[й'а́ н'э пан'имай'у]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я говорю по-английски
            Word(id: "0EBB60FC-478D-46E5-9086-EACB7F7A5454",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "मैं अंग्रेजी बोलता हूँ (Main angrezi bolta hoon)",
                 translation: "I speak English",
                 meaning: "The phrase means that you can speak English.",
                 pronunciation: "[ja ɡɐˈvorʊ pə ˈanɡlʲɪjskʲɪ]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "मैं अंग्रेजी बोलता हूँ (Main angrezi bolta hoon)",
                 meaningOrigin: "इस वाक्यांश का अर्थ है कि आप अंग्रेजी बोल सकते हैं",
                 pronunciationOrigin: "[й'а́ гавар'`у па англ'ийски]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Как вас зовут?
            Word(id: "160CBDE5-0C8A-45A1-8695-B9FE0981DE16",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "आपका नाम क्या है? (Aapka naam kya hai?)",
                 translation: "What is your name?",
                 meaning: "The phrase represents a question about a person's name.",
                 pronunciation: "[kak vas zoˈvut]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "आपका नाम क्या है? (Aapka naam kya hai?)",
                 meaningOrigin: "यह वाक्यांश किसी व्यक्ति के नाम के बारे में एक प्रश्न का प्रतिनिधित्व करता है",
                 pronunciationOrigin: "[к`ак вас завут]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Меня зовут...
            Word(id: "2790F4C0-CB76-4FDB-8574-2C01C63D2B63",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "मेरा नाम है (Mera naam hai)",
                 translation: "My name is...",
                 meaning: "What is your name?",
                 pronunciation: "[mɛˈnʲa zoˈvut]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "मेरा नाम है (Mera naam hai)",
                 meaningOrigin: "मुझे बताओ तुम्हारा नाम क्या है?",
                 pronunciationOrigin: "[м'ин'а завут]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я голоден
            Word(id: "A2D45824-0B9C-4765-AAA1-578255486D80",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "मुझे भूख लगी है (Mujhe bhook lagi hai)",
                 translation: "I'm hungry",
                 meaning: "Feeling of hunger",
                 pronunciation: "[ja ɡɐˈlodʲɪn]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "मुझे भूख लगी है (Mujhe bhook lagi hai)",
                 meaningOrigin: "भूख लगना",
                 pronunciationOrigin: "[й'а г`олад'ин]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я хочу пить
            Word(id: "153A2E04-FD49-4ED6-9351-916BA64D0299",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "मुझे पीने का इच्छा है (Mujhe peene ka ichha hai)",
                 translation: "I want to drink",
                 meaning: "Wish to drink",
                 pronunciation: "[ya khochu pit']",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "मुझे पीने का इच्छा है (Mujhe peene ka ichha hai)",
                 meaningOrigin: "पीने की इच्छा",
                 pronunciationOrigin: "[й'а хач'`у п'`ит']",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: -  Где туалет?
            Word(id: "6A6BF232-00D0-43F8-BED7-E52F0B554DA5",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "शौचालय कहाँ है? (Shouchalay kahan hai?)",
                 translation: "Where is the restroom?",
                 meaning: "Where toilet located",
                 pronunciation: "[gdye tualet]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "शौचालय कहाँ है? (Shouchalay kahan hai?)",
                 meaningOrigin: "शौचालय के स्थान के बारे में प्रश्न",
                 pronunciationOrigin: "[гд'э туʌл❜э́т]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Сколько времени?
            Word(id: "71CDD6E8-192F-456C-B47A-50848892C199",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "घड़ी कितने बजे हैं? (Ghadi kitne baje hain?)",
                 translation: "What time is it?",
                 meaning: "Current time?",
                 pronunciation: "[skol'ko vremeni]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "घड़ी कितने बजे हैं? (Ghadi kitne baje hain?)",
                 meaningOrigin: "वर्तमान समय के बारे में प्रश्न",
                 pronunciationOrigin: "[ск`ол'ка вр'эм'ин'и]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я люблю тебя
            Word(id: "C720C705-B14F-4437-B3A7-DDDA945A0B03",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "मैं तुमसे प्यार करता/करती हूँ (Main tumse pyaar karta/karti hoon)",
                 translation: "I love you",
                 meaning: "Possible expression of love",
                 pronunciation: "[ya lyublyu tebya]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "मैं तुमसे प्यार करता/करती हूँ (Main tumse pyaar karta/karti hoon)",
                 meaningOrigin: "प्रेम की अभिव्यक्ति संभव",
                 pronunciationOrigin: "[й'а л'убл'у т'иб'а́]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Какой прекрасный день!
            Word(id: "E130276F-A64D-4BA2-B5FD-2984C83566B3",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "क्या हसीन दिन है",
                 translation: "What a beautiful day!",
                 meaning: "Positive description of the day",
                 pronunciation: "[kakoy prekrasnyy den']",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "क्या हसीन दिन है",
                 meaningOrigin: "दिन का सकारात्मक वर्णन",
                 pronunciationOrigin: "[какой' пр'икрасный' д'эн']",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Удачи!
            Word(id: "A4963013-0742-4A44-ABEC-141B93C968B7",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "शुभकामनाएँ (Shubhkaamnayein)",
                 translation: "Good luck!",
                 meaning: "Wishing Good luck",
                 pronunciation: "[udachi]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "शुभकामनाएँ (Shubhkaamnayein)",
                 meaningOrigin: "शुभकामनाएँ",
                 pronunciationOrigin: "[удач'и]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Будьте здоровы (после чихания)
            Word(id: "2F69719C-E212-4B74-A4BA-EF514D3643A7",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: " स्वस्थ रहो (Swasth raho)",
                 translation: "Bless you! (after sneezing)",
                 meaning: "Wishing good health",
                 pronunciation: "[bud'te zdorovy]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: " स्वस्थ रहो (Swasth raho)",
                 meaningOrigin: "जिस व्यक्ति को छींक आ रही है उसके स्वस्थ होने की कामना करें",
                 pronunciationOrigin: "[б`уд'т'э здаровы]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - До свидания!
            Word(id: "2CEEA866-D1FD-4975-ADFC-0731D73E4021",
                 fromLang: .Hindi,
                 toLang: .English,
                 word: "फिर मिलेंगे (Phir milenge)",
                 translation: "Goodbye!",
                 meaning: "Farewell",
                 pronunciation: "[da svidaniya]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "फिर मिलेंगे (Phir milenge)",
                 meaningOrigin: "जुदाई",
                 pronunciationOrigin: "[дасв'идан'`ий'а]",
                 languageLinkList: demoCategoriesLinkVol1),
            
        ]
    }
}
