//
//  WordAssetDemo.swift
//  Learn Up
//
//  Created by PowerMac on 17.01.2024.
//

import Foundation

class WordAssetDemoJapanese: WordAssetProtocol {
    static var wordCategory = CategoryWords(title: "25 Japanese Words & Phrases Vol.1", language: .Japanese, id: "japaneseDemo", wordList: loadWordList(), isPremium: false, assetPath: LearnUpConfiguration.baseCategoryAssetPath)
    
    static func loadWordList() -> [Word] {
        return [
            // MARK: - Здраствуйте
            Word(id: "528BC134-44D5-4334-A029-C0E1DB97BA50",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "こんにちは (Konnichiwa)",
         
                 translation: "",
             
                 meaning: "",
                  
                 pronunciation: "",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "こんにちは (Konnichiwa)",
                 meaningOrigin: "通常、初対面のときや見知らぬ人とコミュニケーションをとるときに使用される正式な挨拶",
                 pronunciationOrigin: "[здр`аствуй'т'э]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Спасибо
            Word(id: "C55273C3-CB85-4E70-B894-ACE0725DDB96",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "ありがとう (Arigatou)",
                 translation: "Thank you",
                 meaning: "expression of gratitude",
                 pronunciation: "[spəsʲɪ'bo]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "ありがとう (Arigatou)",
                 meaningOrigin: "感謝の粒子表現",
                 pronunciationOrigin: "[спа-си́-бо]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Пожалуйста
            Word(id: "2E81E660-EB45-4299-BC3D-1FBBF0AC38BD",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "お願いします (Onegaishimasu)",
                 translation: "Please",
                 meaning: "Polite expressions of address, request, response to gratitude",
                 pronunciation: "[ˌpliːzɡlædˈliː]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "お願いします (Onegaishimasu)",
                 meaningOrigin: "丁寧な挨拶、お願い、感謝の返事を表現する",
                 pronunciationOrigin: "[пажалуй’ста]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Простите
            Word(id: "1E8C1BB5-D296-42B0-877B-00E660741CAF",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "ごめんなさい (Gomen nasai)",
                 translation: "Excuse me",
                 meaning: "Regret for causing inconvenience, discomfort, or distress",
                 pronunciation: "[Prəˈstaɪt]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "ごめんなさい (Gomen nasai)",
                 meaningOrigin: "引き起こされた騒動、不便、苦痛による遺憾の意",
                 pronunciationOrigin: "[изв’ин’ит’э]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Да
            Word(id: "EE08B5F3-8A30-41FA-9065-CA7B4B3F11BB",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "はい (Hai)",
                 translation: "Yes",
                 meaning: "Agreement with something",
                 pronunciation: "[dæ]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "はい (Hai)",
                 meaningOrigin: "何かに同意する",
                 pronunciationOrigin: "[да]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Нет
            Word(id: "9A12A29A-5842-46E9-8B4A-397E4894E13F",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "いいえ (Iie)",
                 translation: "",
                 meaning: "Disagreement with something",
                 pronunciation: "[nɛt]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "いいえ (Iie)",
                 meaningOrigin: "何かに同意できない",
                 pronunciationOrigin: "[н’эт]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Как дела?
            Word(id: "FAC41092-A1DC-4129-9FB4-AF2B0C2CD079",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "お元気ですか？ (Ogenki desu ka?)",
                 translation: "How are you?",
                 meaning: "Greetings, inquiry about current state of affairs.",
                 pronunciation: "[kak dʲɪˈla]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "お元気ですか？ (Ogenki desu ka?)",
                 meaningOrigin: "挨拶、近況についての質問",
                 pronunciationOrigin: "[к`ак д'ила]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Хорошо
            Word(id: "989D6AEE-BD35-4A75-BFA1-4B418C57BE8E",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "元気です (Genki desu)",
                 translation: "Good",
                 meaning: "As is customary, what is considered beautiful, correct.",
                 pronunciation: "[xɐˈroʂə.]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "元気です (Genki desu)",
                 meaningOrigin: "あるべき姿、美しいと思われるもの、正しいもの",
                 pronunciationOrigin: "[харашо]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Плохо
            Word(id: "80109E60-838D-45A7-97E6-8030907FE5CF",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "元気ではない (Genki dewa nai)",
                 translation: "Bad",
                 meaning: "Appraisal or expression of dissatisfaction, disappointment",
                 pronunciation: "[ˈploxə]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "元気ではない (Genki dewa nai)",
                 meaningOrigin: "不満、失望の評価または表現",
                 pronunciationOrigin: "[пл`оха]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Где это?
            Word(id: "BB85F13B-373B-4AE9-B787-4F5D18584F7D",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "それはどこですか？ (Sore wa doko desu ka?)",
                 translation: "Where is this?",
                 meaning: "Request for the location or positioning of something.",
                 pronunciation: "[ɡdʲe ɛˈto]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "それはどこですか？ (Sore wa doko desu ka?)",
                 meaningOrigin: "何かの場所または場所を要求する",
                 pronunciationOrigin: "[гд'э эта]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Сколько это стоит?
            Word(id: "C7C1215F-546A-4A98-8A63-6AA891BC865B",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "いくらですか？ (Ikura desu ka?)",
                 translation: "How much does it cost?",
                 meaning: "Inquiry about the price of a specific product or service",
                 pronunciation: "[ˈskolʲkə ɛˈto stojɪt]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "いくらですか？ (Ikura desu ka?)",
                 meaningOrigin: "製品またはサービスの価格をリクエストする",
                 pronunciationOrigin: "[ск`ол'ка эта стои́т]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Можно помочь?
            Word(id: "ACFBC464-D657-4E84-8F09-F0E99C6C4937",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "お手伝いしましょうか？ (O-tetsudai shimashou ka?)",
                 translation: "Can you help?",
                 meaning: "Expression of readiness to provide assistance or support",
                 pronunciation: "[ˈmoʐnə pamɐʂˈtʲi.]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "お手伝いしましょうか？ (O-tetsudai shimashou ka?)",
                 meaningOrigin: "支援や支援を提供する用意があることの表明",
                 pronunciationOrigin: "[можна пам`оч']",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я не понимаю
            Word(id: "E2794BD0-19E2-4130-8D36-88D473D70BD0",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "わかりません (Wakarimasen)",
                 translation: "I don't understand",
                 meaning: "Expression of not understanding something.",
                 pronunciation: "[ja nʲɪ pɐnʲɪˈmaju]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "わかりません (Wakarimasen)",
                 meaningOrigin: "話者が何かを理解していないことを表現する",
                 pronunciationOrigin: "[й'а́ н'э пан'имай'у]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я говорю по-английски
            Word(id: "0EBB60FC-478D-46E5-9086-EACB7F7A5454",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "私は英語を話します (Watashi wa Eigo o hanashimasu)",
                 translation: "I speak English",
                 meaning: "The phrase means that you can speak English.",
                 pronunciation: "[ja ɡɐˈvorʊ pə ˈanɡlʲɪjskʲɪ]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "私は英語を話します (Watashi wa Eigo o hanashimasu)",
                 meaningOrigin: "このフレーズはあなたが英語を話すことができることを意味します",
                 pronunciationOrigin: "[й'а́ гавар'`у па англ'ийски]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Как вас зовут?
            Word(id: "160CBDE5-0C8A-45A1-8695-B9FE0981DE16",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "お名前は何ですか？ (Onamae wa nan desu ka?)",
                 translation: "What is your name?",
                 meaning: "The phrase represents a question about a person's name.",
                 pronunciation: "[kak vas zoˈvut]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "お名前は何ですか？ (Onamae wa nan desu ka?)",
                 meaningOrigin: "このフレーズは人の名前に関する質問を表します",
                 pronunciationOrigin: "[к`ак вас завут]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Меня зовут...
            Word(id: "2790F4C0-CB76-4FDB-8574-2C01C63D2B63",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "私の名前は... (Watashi no namae wa...)",
                 translation: "My name is...",
                 meaning: "What is your name?",
                 pronunciation: "[mɛˈnʲa zoˈvut]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "私の名前は... (Watashi no namae wa...)",
                 meaningOrigin: "あなたの名前は何なのか教えてください",
                 pronunciationOrigin: "[м'ин'а завут]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я голоден
            Word(id: "A2D45824-0B9C-4765-AAA1-578255486D80",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "お腹がすいています (Onaka ga akimashita)",
                 translation: "I'm hungry",
                 meaning: "Feeling of hunger",
                 pronunciation: "[ja ɡɐˈlodʲɪn]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "お腹がすいています (Onaka ga suiteimasu)",
                 meaningOrigin: "空腹感",
                 pronunciationOrigin: "[й'а г`олад'ин]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я хочу пить
            Word(id: "153A2E04-FD49-4ED6-9351-916BA64D0299",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "私は飲みたいです (Watashi wa nomitaidesu)",
                 translation: "I want to drink",
                 meaning: "Wish to drink",
                 pronunciation: "[ya khochu pit']",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "飲み物が欲しいです (Nomimono ga hoshii desu)",
                 meaningOrigin: "飲酒欲求",
                 pronunciationOrigin: "[й'а хач'`у п'`ит']",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: -  Где туалет?
            Word(id: "6A6BF232-00D0-43F8-BED7-E52F0B554DA5",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "トイレはどこですか？ (Toire wa doko desu ka?)",
                 translation: "Where is the restroom?",
                 meaning: "Where toilet located",
                 pronunciation: "[gdye tualet]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "トイレはどこですか？ (Toire wa doko desu ka?)",
                 meaningOrigin: "トイレの場所についての質問",
                 pronunciationOrigin: "[гд'э туʌл❜э́т]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Сколько времени?
            Word(id: "71CDD6E8-192F-456C-B47A-50848892C199",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "今何時ですか？ (Ima nan-ji desu ka?)",
                 translation: "What time is it?",
                 meaning: "Current time?",
                 pronunciation: "[skol'ko vremeni]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "今何時ですか？ (Ima nan-ji desu ka?)",
                 meaningOrigin: "現在時刻についての質問",
                 pronunciationOrigin: "[ск`ол'ка вр'эм'ин'и]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я люблю тебя
            Word(id: "C720C705-B14F-4437-B3A7-DDDA945A0B03",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "愛しています (Aishiteimasu)",
                 translation: "I love you",
                 meaning: "Possible expression of love",
                 pronunciation: "[ya lyublyu tebya]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "愛しています (Aishiteimasu)",
                 meaningOrigin: "愛情表現の可能性",
                 pronunciationOrigin: "[й'а л'убл'у т'иб'а́]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Какой прекрасный день!
            Word(id: "E130276F-A64D-4BA2-B5FD-2984C83566B3",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "素敵な一日ですね (Suteki na ichinichi desu ne)",
                 translation: "What a beautiful day!",
                 meaning: "Positive description of the day",
                 pronunciation: "[kakoy prekrasnyy den']",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "素敵な一日ですね (Suteki na ichinichi desu ne)",
                 meaningOrigin: "その日のポジティブな説明",
                 pronunciationOrigin: "[какой' пр'икрасный' д'эн']",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Удачи!
            Word(id: "A4963013-0742-4A44-ABEC-141B93C968B7",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "幸運を (Kōun o)",
                 translation: "Good luck!",
                 meaning: "Wishing Good luck",
                 pronunciation: "[udachi]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "運がありますように (Un ga arimasu you ni)",
                 meaningOrigin: "幸運を願っています",
                 pronunciationOrigin: "[удач'и]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Будьте здоровы (после чихания)
            Word(id: "2F69719C-E212-4B74-A4BA-EF514D3643A7",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "お大事に (Odaiji ni)",
                 translation: "Bless you! (after sneezing)",
                 meaning: "Wishing good health",
                 pronunciation: "[bud'te zdorovy]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "お大事に (Odaiji ni)",
                 meaningOrigin: "くしゃみをしている人が健康になりますように",
                 pronunciationOrigin: "[б`уд'т'э здаровы]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - До свидания!
            Word(id: "2CEEA866-D1FD-4975-ADFC-0731D73E4021",
                 fromLang: .Japanese,
                 toLang: .English,
                 word: "さようなら (Sayonara)",
                 translation: "Goodbye!",
                 meaning: "Farewell",
                 pronunciation: "[da svidaniya]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "さようなら (Sayonara)",
                 meaningOrigin: "別れ",
                 pronunciationOrigin: "[дасв'идан'`ий'а]",
                 languageLinkList: demoCategoriesLinkVol1),
            
        ]
    }
}
