//
//  WordAssetDemo.swift
//  Learn Up
//
//  Created by PowerMac on 17.01.2024.
//

import Foundation

class WordAssetDemoFrench: WordAssetProtocol {
    static var wordCategory = CategoryWords(title: "25 French Words & Phrases Vol.1", language: .French, id: "frenchDemo", wordList: loadWordList(), isPremium: false, assetPath: LearnUpConfiguration.baseCategoryAssetPath)
    
    static func loadWordList() -> [Word] {
        return [
            // MARK: - Здраствуйте
            Word(id: "528BC134-44D5-4334-A029-C0E1DB97BA50",
                 fromLang: .French,
                 toLang: .English,
                 word: "Bonjour",
         
                 translation: "",
             
                 meaning: "",
                  
                 pronunciation: "",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Bonjour",
                 meaningOrigin: "Félicitations, expression de joie ou de louanges pour les réalisations ou la bonne fortune de quelqu'un.",
                 pronunciationOrigin: "[здр`аствуй'т'э]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Спасибо
            Word(id: "C55273C3-CB85-4E70-B894-ACE0725DDB96",
                 fromLang: .French,
                 toLang: .English,
                 word: "Merci",
                 translation: "Thank you",
                 meaning: "expression of gratitude",
                 pronunciation: "[spəsʲɪ'bo]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Merci",
                 meaningOrigin: "Expression polie de gratitude ou d'appréciation.",
                 pronunciationOrigin: "[спа-си́-бо]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Пожалуйста
            Word(id: "2E81E660-EB45-4299-BC3D-1FBBF0AC38BD",
                 fromLang: .French,
                 toLang: .English,
                 word: "S'il vous plaît",
                 translation: "Please",
                 meaning: "Polite expressions of address, request, response to gratitude",
                 pronunciation: "[ˌpliːzɡlædˈliː]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "S'il vous plaît",
                 meaningOrigin: "Expression polie utilisée pour faire des demandes ou donner de l'emphase à une commande polie.",
                 pronunciationOrigin: "[пажалуй’ста]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Простите
            Word(id: "1E8C1BB5-D296-42B0-877B-00E660741CAF",
                 fromLang: .French,
                 toLang: .English,
                 word: "Простите",
                 translation: "Excusez-moi",
                 meaning: "Regret for causing inconvenience, discomfort, or distress",
                 pronunciation: "[Prəˈstaɪt]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Excusez-moi",
                 meaningOrigin: "Expression de regret, demande de pardon ou reconnaissance d'une erreur.",
                 pronunciationOrigin: "[изв’ин’ит’э]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Да
            Word(id: "EE08B5F3-8A30-41FA-9065-CA7B4B3F11BB",
                 fromLang: .French,
                 toLang: .English,
                 word: "Oui",
                 translation: "Yes",
                 meaning: "Agreement with something",
                 pronunciation: "[dæ]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Oui",
                 meaningOrigin: "Réponse affirmative indiquant l'accord ou l'affirmation.",
                 pronunciationOrigin: "[да]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Нет
            Word(id: "9A12A29A-5842-46E9-8B4A-397E4894E13F",
                 fromLang: .French,
                 toLang: .English,
                 word: "Non",
                 translation: "",
                 meaning: "Disagreement with something",
                 pronunciation: "[nɛt]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Non",
                 meaningOrigin: "Réponse négative indiquant le désaccord ou la négation.",
                 pronunciationOrigin: "[н’эт]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Как дела?
            Word(id: "FAC41092-A1DC-4129-9FB4-AF2B0C2CD079",
                 fromLang: .French,
                 toLang: .English,
                 word: "Comment ça va?",
                 translation: "How are you?",
                 meaning: "Greetings, inquiry about current state of affairs.",
                 pronunciation: "[kak dʲɪˈla]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Comment ça va?",
                 meaningOrigin: "Salutation courante demandant comment une personne va.",
                 pronunciationOrigin: "[к`ак д'ила]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Хорошо
            Word(id: "989D6AEE-BD35-4A75-BFA1-4B418C57BE8E",
                 fromLang: .French,
                 toLang: .English,
                 word: "Bien",
                 translation: "Good",
                 meaning: "As is customary, what is considered beautiful, correct.",
                 pronunciation: "[xɐˈroʂə.]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Bien",
                 meaningOrigin: "Réponse indiquant que tout va bien ou que la personne se porte bien.",
                 pronunciationOrigin: "[харашо]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Плохо
            Word(id: "80109E60-838D-45A7-97E6-8030907FE5CF",
                 fromLang: .French,
                 toLang: .English,
                 word: "Mal",
                 translation: "Bad",
                 meaning: "Appraisal or expression of dissatisfaction, disappointment",
                 pronunciation: "[ˈploxə]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Mal",
                 meaningOrigin: "Réponse indiquant que quelque chose ne va pas bien ou que la personne ne se sent pas bien.",
                 pronunciationOrigin: "[пл`оха]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Где это?
            Word(id: "BB85F13B-373B-4AE9-B787-4F5D18584F7D",
                 fromLang: .French,
                 toLang: .English,
                 word: "Où est-ce?",
                 translation: "Where is this?",
                 meaning: "Request for the location or positioning of something.",
                 pronunciation: "[ɡdʲe ɛˈto]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Où est-ce?",
                 meaningOrigin: "Demande sur l'emplacement de quelque chose.",
                 pronunciationOrigin: "[гд'э эта]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Сколько это стоит?
            Word(id: "C7C1215F-546A-4A98-8A63-6AA891BC865B",
                 fromLang: .French,
                 toLang: .English,
                 word: "Combien ça coûte?",
                 translation: "How much does it cost?",
                 meaning: "Inquiry about the price of a specific product or service",
                 pronunciation: "[ˈskolʲkə ɛˈto stojɪt]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Combien ça coûte?",
                 meaningOrigin: "Demande sur le prix de quelque chose.",
                 pronunciationOrigin: "[ск`ол'ка эта стои́т]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Можно помочь?
            Word(id: "ACFBC464-D657-4E84-8F09-F0E99C6C4937",
                 fromLang: .French,
                 toLang: .English,
                 word: "Puis-je vous aider?",
                 translation: "Can you help?",
                 meaning: "Expression of readiness to provide assistance or support",
                 pronunciation: "[ˈmoʐnə pamɐʂˈtʲi.]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Puis-je vous aider?",
                 meaningOrigin: "Offre d'assistance ou demande si quelqu'un a besoin d'aide.",
                 pronunciationOrigin: "[можна пам`оч']",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я не понимаю
            Word(id: "E2794BD0-19E2-4130-8D36-88D473D70BD0",
                 fromLang: .French,
                 toLang: .English,
                 word: "Je ne comprends pas",
                 translation: "I don't understand",
                 meaning: "Expression of not understanding something.",
                 pronunciation: "[ja nʲɪ pɐnʲɪˈmaju]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Je ne comprends pas",
                 meaningOrigin: "Expression indiquant une absence de compréhension.",
                 pronunciationOrigin: "[й'а́ н'э пан'имай'у]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я говорю по-английски
            Word(id: "0EBB60FC-478D-46E5-9086-EACB7F7A5454",
                 fromLang: .French,
                 toLang: .English,
                 word: "Je parle anglais",
                 translation: "I speak English",
                 meaning: "The phrase means that you can speak English.",
                 pronunciation: "[ja ɡɐˈvorʊ pə ˈanɡlʲɪjskʲɪ]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Je parle anglais ",
                 meaningOrigin: "Déclaration de la capacité à communiquer en anglais.",
                 pronunciationOrigin: "[й'а́ гавар'`у па англ'ийски]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Как вас зовут?
            Word(id: "160CBDE5-0C8A-45A1-8695-B9FE0981DE16",
                 fromLang: .French,
                 toLang: .English,
                 word: "Comment vous appelez-vous?",
                 translation: "What is your name?",
                 meaning: "The phrase represents a question about a person's name.",
                 pronunciation: "[kak vas zoˈvut]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Comment vous appelez-vous?",
                 meaningOrigin: "Demande du nom de quelqu'un.",
                 pronunciationOrigin: "[к`ак вас завут]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Меня зовут...
            Word(id: "2790F4C0-CB76-4FDB-8574-2C01C63D2B63",
                 fromLang: .French,
                 toLang: .English,
                 word: "Je m'appelle",
                 translation: "My name is...",
                 meaning: "What is your name?",
                 pronunciation: "[mɛˈnʲa zoˈvut]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Je m'appelle",
                 meaningOrigin: "Présentation de soi en indiquant son propre nom.",
                 pronunciationOrigin: "[м'ин'а завут]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я голоден
            Word(id: "A2D45824-0B9C-4765-AAA1-578255486D80",
                 fromLang: .French,
                 toLang: .English,
                 word: "J'ai faim",
                 translation: "I'm hungry",
                 meaning: "Feeling of hunger",
                 pronunciation: "[ja ɡɐˈlodʲɪn]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "J'ai faim",
                 meaningOrigin: "Expression indiquant la sensation de faim.",
                 pronunciationOrigin: "[й'а г`олад'ин]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я хочу пить
            Word(id: "153A2E04-FD49-4ED6-9351-916BA64D0299",
                 fromLang: .French,
                 toLang: .English,
                 word: "Je veux boire",
                 translation: "I want to drink",
                 meaning: "Wish to drink",
                 pronunciation: "[ya khochu pit']",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Je veux boire",
                 meaningOrigin: "Expression exprimant le désir de boire quelque chose.",
                 pronunciationOrigin: "[й'а хач'`у п'`ит']",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: -  Где туалет?
            Word(id: "6A6BF232-00D0-43F8-BED7-E52F0B554DA5",
                 fromLang: .French,
                 toLang: .English,
                 word: "Où sont les toilettes?",
                 translation: "Where is the restroom?",
                 meaning: "Where toilet located",
                 pronunciation: "[gdye tualet]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Où sont les toilettes?",
                 meaningOrigin: "Demande sur l'emplacement des toilettes.",
                 pronunciationOrigin: "[гд'э туʌл❜э́т]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Сколько времени?
            Word(id: "71CDD6E8-192F-456C-B47A-50848892C199",
                 fromLang: .French,
                 toLang: .English,
                 word: "Quelle heure est-il?",
                 translation: "What time is it?",
                 meaning: "Current time?",
                 pronunciation: "[skol'ko vremeni]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Quelle heure est-il?",
                 meaningOrigin: "Question sur l'heure actuelle.",
                 pronunciationOrigin: "[ск`ол'ка вр'эм'ин'и]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Я люблю тебя
            Word(id: "C720C705-B14F-4437-B3A7-DDDA945A0B03",
                 fromLang: .French,
                 toLang: .English,
                 word: "Je t'aime",
                 translation: "I love you",
                 meaning: "Possible expression of love",
                 pronunciation: "[ya lyublyu tebya]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Je t'aime",
                 meaningOrigin: "Expression de profond affection ou de sentiments romantiques.",
                 pronunciationOrigin: "[й'а л'убл'у т'иб'а́]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Какой прекрасный день!
            Word(id: "E130276F-A64D-4BA2-B5FD-2984C83566B3",
                 fromLang: .French,
                 toLang: .English,
                 word: "Quelle belle journée!",
                 translation: "What a beautiful day!",
                 meaning: "Positive description of the day",
                 pronunciation: "[kakoy prekrasnyy den']",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Quelle belle journée!",
                 meaningOrigin: "Expression d'admiration pour la belle journée ou le temps agréable.",
                 pronunciationOrigin: "[какой' пр'икрасный' д'эн']",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Удачи!
            Word(id: "A4963013-0742-4A44-ABEC-141B93C968B7",
                 fromLang: .French,
                 toLang: .English,
                 word: "Bonne chance",
                 translation: "Good luck!",
                 meaning: "Wishing Good luck",
                 pronunciation: "[udachi]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Bonne chance",
                 meaningOrigin: "Souhait de succès ou de bonne fortune.",
                 pronunciationOrigin: "[удач'и]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - Будьте здоровы (после чихания)
            Word(id: "2F69719C-E212-4B74-A4BA-EF514D3643A7",
                 fromLang: .French,
                 toLang: .English,
                 word: "À vos souhaits",
                 translation: "Bless you! (after sneezing)",
                 meaning: "Wishing good health",
                 pronunciation: "[bud'te zdorovy]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "À vos souhaits",
                 meaningOrigin: "Expression habituelle souhaitant une bonne santé après qu'une personne a éternué.",
                 pronunciationOrigin: "[б`уд'т'э здаровы]",
                 languageLinkList: demoCategoriesLinkVol1),
            // MARK: - До свидания!
            Word(id: "2CEEA866-D1FD-4975-ADFC-0731D73E4021",
                 fromLang: .French,
                 toLang: .English,
                 word: "Au revoir",
                 translation: "Goodbye!",
                 meaning: "Farewell",
                 pronunciation: "[da svidaniya]",
                 trDate: Date.now,
                 isLearned: false,
                 translationOrigin: "Au revoir",
                 meaningOrigin: "Expression de départ, indiquant la fin d'une conversation.",
                 pronunciationOrigin: "[дасв'идан'`ий'а]",
                 languageLinkList: demoCategoriesLinkVol1),
            
        ]
    }
}
